source "https://rubygems.org"
ruby "4.0.7"

gem "rails", "8.1.3.1"
gem "propshaft"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "sqlite3", ">= 2.1"
end

group :production do
  gem "pg"
end
